config/routes.rb
Mypsql::Application.routes.draw do
  
  get "home/index"
  get "home/show"
  resources :galleries

  resources :paintings do
   member do
     get 'publish'
   end
  end
  match 'getmycode', to: 'paintings#getmycode'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :posts

  root :to => 'home#index'

end

app/models/painting.rb
class Painting < ActiveRecord::Base
 attr_accessible :gallery_id, :name, :image, :remote_image_url
  belongs_to :gallery
  mount_uploader :image, ImageUploader
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

  def new
    @painting = Painting.new(:gallery_id => params[:gallery_id])
  end

  def create
    @painting = Painting.new(params[:painting])
    if @painting.save
      flash[:notice] = "Successfully created painting."
      redirect_to @painting.gallery
    else
      render :action => 'new'
    end
  end

  def edit
    @painting = Painting.find(params[:id])

  end

  def publish
      @painting = Painting.find(params[:id])
            token = params[:token]
      begin

        graph = Koala::Facebook::API.new(token)
        if graph
          graph.put_picture(@painting.image.path,{:message => "Make my ColorCode"})
        end
        redirect_to  home_show_path, notice: "Review has been created."
      
      rescue
        redirect_to  getmycode_path, notice: "Please Login with Facebook."
      end



  end

  def getmycode
      @token = params[:token]

      @random_image = Painting.first(:order => "RANDOM()")

  end

  def show
    @painting = Painting.find(params[:id])

  end

  def update
    @painting = Painting.find(params[:id])
    if @painting.update_attributes(params[:painting])
      flash[:notice] = "Successfully updated painting."
      redirect_to @painting.gallery
    else
      render :action => 'edit'
    end
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    flash[:notice] = "Successfully destroyed painting."
    redirect_to @painting.gallery
  end
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/paintings/_form.html.erb
<%= form_for @painting, :html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :gallery_id %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :remote_image_url, "or image URL" %>
    <%= f.text_field :remote_image_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/paintings/edit.html.erb
<% title "Edit Painting" %>

<%= render 'form' %>

<p><%= link_to "Back to Gallery", @painting.gallery %></p>

app/views/paintings/getmycode.html.erb
 <script> 
      function postToFeed() {

        // calling the API ...
        var obj = {
          method: 'feed',
          link: 'http://sheltered-wildwood-4199.herokuapp.com/',
          picture: 'http://sheltered-wildwood-4199.herokuapp.com/<%=@random_image.image_url(:large) %>',
          source: 'http://sheltered-wildwood-4199.herokuapp.com/<%=@random_image.image_url(:large) %>',
          name: 'Get my own Code with COLORCODE',
          caption: 'Reference Documentation',
          description: 'Using Dialogs to interact with users.'
        };

        function callback(response) {
       //   document.getElementById('msg').innerHTML = "Post ID: " + response['post_id'];
        }

        FB.ui(obj, callback);
      }
    
 </script>
 <p id="notice"><%= notice %></p>
<h2><%= @random_image.name%></h2>

<p id='msg'></p>

<p >
<%=  image_tag @random_image.image_url(:large) if @random_image.image? %>
</p>

<p style="text-align:center">
  <%= link_to "Post to my wall", publish_painting_path(@random_image,:token => @token ), :class => "btn btn-success btn-large" %>
</p>
<p><a onclick='postToFeed(); return false;' class ="btn btn-success btn-large" >Post to Feed</a></p>

app/views/paintings/new.html.erb
<% title "New Painting" %>

<%= render 'form' %>

<p><%= link_to "Back to Gallery", @painting.gallery %></p>

app/views/paintings/show.html.erb
<% title @painting.name %>

<div id="paintings">
    <div class="painting">
      <%=  image_tag @painting.image_url(:large) if @painting.image? %>
      <div class="name"><%= @painting.name %></div>
      <div class="actions">
        <%= link_to "remove", @painting, :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>
  <div class="clear"></div>
</div>

<p>
    <td><%= link_to 'Back', @painting.gallery %></td>
</p>