config/routes.rb
Mypsql::Application.routes.draw do
  
  get "home/index"
  get "home/show"
  resources :galleries

  resources :paintings do
   member do
     get 'publish'
   end
  end
  match 'getmycode', to: 'paintings#getmycode'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :posts

  root :to => 'home#index'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#">
<head>
<title>ColorCode</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>    
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '387404467992646', // App ID
      channelUrl : '//'+window.location.hostname+'/channel.html', // Path to your Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    // Additional initialization code here


  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
</script>

<div id="container" class="container">
  <div class="row">
      <div class="span12"> 
            <div id="user_nav">
              <div class="fb-login-button" data-show-faces="true" data-width="200" data-max-rows="1"></div>
            </div>
          <div class="hero-unit"><%= yield %></div>
      </div>
  </div>
  <div class="row">
    <div class="span12">
      <ul class="thumbnails">
        <li class="span3">
          <a href="#" class="thumbnail">
            <%=  image_tag  "code1.jpg" ,:size => "120x120" %>
          </a>
        </li>
        <li class="span3">
          <a href="#" class="thumbnail">
            <%=  image_tag  "code2.jpg" ,:size => "120x120" %>
          </a>
        </li>
        <li class="span3">
          <a href="#" class="thumbnail">
            <%=  image_tag  "code3.jpg" ,:size => "120x120" %>
          </a>
        </li>
        <li class="span3">
          <a href="#" class="thumbnail">
            <%=  image_tag  "code4.jpg" ,:size => "120x120" %>
          </a>
        </li>
      </ul>
     </div> 
  </div>

<div class="fb-comments" data-href="https://www.facebook.com/pages/MyCode/181525571977095" data-num-posts="10" data-width="450"> </div>

 <%= link_to "Galleries", galleries_path , :class => "btn btn-info" %> 
</div>



</body>
</html>